import SwiftUI

struct DisclaimerView: View {
    @Binding var isPresented: Bool
    
    var body: some View {
        NavigationView {
            ScrollView {
                VStack(alignment: .leading, spacing: 20) {
                    // Header
                    VStack(alignment: .leading, spacing: 10) {
                        HStack {
                            Image(systemName: "exclamationmark.triangle.fill")
                                .foregroundColor(.orange)
                                .font(.title2)
                            Text("Important Disclaimer")
                                .font(.title2)
                                .fontWeight(.bold)
                        }
                        
                        Text("Please read this important information before using TherapAI.")
                            .font(.subheadline)
                            .foregroundColor(.secondary)
                    }
                    
                    // Medical Disclaimer
                    DisclaimerSection(
                        title: "Medical Disclaimer",
                        icon: "stethoscope",
                        iconColor: .red,
                        content: """
                        TherapAI is NOT a substitute for professional medical advice, diagnosis, or treatment. This app is designed for informational and wellness support purposes only.
                        
                        • Always seek advice from qualified healthcare providers
                        • Do not delay seeking medical attention because of information from this app
                        • This app does not provide emergency services
                        • AI responses are not professional therapy or medical advice
                        """
                    )
                    
                    // Crisis Resources
                    DisclaimerSection(
                        title: "Crisis & Emergency Resources",
                        icon: "phone.fill",
                        iconColor: .red,
                        content: """
                        If you are experiencing a mental health emergency or having thoughts of suicide:
                        
                        🚨 Emergency Services: 911 (US) or your local emergency number
                        
                        📞 Crisis Hotlines:
                        • National Suicide Prevention Lifeline: 988
                        • Crisis Text Line: Text HOME to 741741
                        • SAMHSA Helpline: 1-800-662-4357
                        
                        🌐 Online Resources:
                        • National Suicide Prevention Lifeline: suicidepreventionlifeline.org
                        • Crisis Text Line: crisistextline.org
                        """
                    )
                    
                    // AI Limitations
                    DisclaimerSection(
                        title: "AI Assistant Limitations",
                        icon: "brain.head.profile",
                        iconColor: .blue,
                        content: """
                        Our AI assistant has limitations:
                        
                        • Responses are generated by artificial intelligence
                        • May not always provide accurate information
                        • Cannot replace human professional judgment
                        • Not trained on your specific medical history
                        • May misunderstand context or nuance
                        """
                    )
                    
                    // Privacy Notice
                    DisclaimerSection(
                        title: "Privacy & Data",
                        icon: "lock.shield",
                        iconColor: .green,
                        content: """
                        Your privacy is important to us:
                        
                        • Conversations are encrypted and secure
                        • Data is not shared with unauthorized parties
                        • You can delete your data at any time
                        • See our Privacy Policy for full details
                        """
                    )
                    
                    // Professional Recommendation
                    VStack(alignment: .leading, spacing: 15) {
                        Text("🏥 We Recommend")
                            .font(.headline)
                            .fontWeight(.semibold)
                        
                        Text("Consider professional therapy or counseling for ongoing mental health support. TherapAI can complement but not replace professional care.")
                            .font(.body)
                            .padding(.horizontal, 15)
                            .padding(.vertical, 12)
                            .background(Color.blue.opacity(0.1))
                            .cornerRadius(10)
                    }
                    
                    // Acknowledgment
                    VStack(spacing: 15) {
                        Text("By continuing to use TherapAI, you acknowledge that you have read and understood these disclaimers.")
                            .font(.footnote)
                            .foregroundColor(.secondary)
                            .multilineTextAlignment(.center)
                        
                        Button("I Understand") {
                            isPresented = false
                        }
                        .frame(maxWidth: .infinity)
                        .frame(height: 50)
                        .background(Color.blue)
                        .foregroundColor(.white)
                        .cornerRadius(10)
                        .fontWeight(.medium)
                    }
                    .padding(.top, 10)
                }
                .padding()
            }
            .navigationTitle("Disclaimers")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Close") {
                        isPresented = false
                    }
                }
            }
        }
    }
}

struct DisclaimerSection: View {
    let title: String
    let icon: String
    let iconColor: Color
    let content: String
    
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                Image(systemName: icon)
                    .foregroundColor(iconColor)
                    .font(.title3)
                Text(title)
                    .font(.headline)
                    .fontWeight(.semibold)
            }
            
            Text(content)
                .font(.body)
                .fixedSize(horizontal: false, vertical: true)
        }
        .padding(.horizontal, 15)
        .padding(.vertical, 12)
        .background(Color(.systemGray6))
        .cornerRadius(12)
    }
}

// Compact disclaimer banner for chat interface
struct CompactDisclaimerBanner: View {
    @State private var showingFullDisclaimer = false
    
    var body: some View {
        HStack {
            Image(systemName: "exclamationmark.triangle.fill")
                .foregroundColor(.orange)
                .font(.caption)
            
            Text("AI responses are not professional therapy.")
                .font(.caption)
                .foregroundColor(.secondary)
            
            Spacer()
            
            Button("Learn More") {
                showingFullDisclaimer = true
            }
            .font(.caption)
            .foregroundColor(.blue)
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 8)
        .background(Color.orange.opacity(0.1))
        .cornerRadius(8)
        .sheet(isPresented: $showingFullDisclaimer) {
            DisclaimerView(isPresented: $showingFullDisclaimer)
        }
    }
}

#Preview {
    DisclaimerView(isPresented: .constant(true))
}